% runExcelExport  Full single-run pipeline with comprehensive Excel export.
%
% Sheets exported:
%   1.  Annual              — Annual FX results (TI, OCI, CC variants)
%   2.  Quarterly           — Quarterly FX results
%   3.  Daily_PortfolioValue— V_EUR, V_SEK, all constant-currency runs
%   4.  Daily_FXImpact      — Daily FX attribution (trans/transl/CC)
%   5.  Daily_PAMTerms      — All 13 PAM P&L decomposition terms (EUR)
%   6.  Daily_FXRates       — All spot FX rates to EUR and SEK
%   7.  Daily_CashHoldings  — Cash by currency (local + EUR equivalent)
%   8.  Daily_Instruments   — Instrument holdings by currency (EUR equiv)
%   9.  Daily_Transactions  — Buy/sell volumes by currency (EUR equiv)
%   10. PortfolioSummary    — V_EUR decomposition check
%   11. PurchaseOrders      — Raw purchase order records
%   12. StockTransactions   — Raw stock transaction records
%   13. AccountsReceivable  — Raw AR records
%   14. AccountsPayable     — Raw AP records
%   15. Sales               — Raw sales invoice records
%   16. BOM                 — Bill of materials records
%
% Output: PAM_full_export.xlsx  (saved to Exjobb_FX root folder)

cd('C:/Users/jhybn/Desktop/exjobb/Exjobb_FX/matlabExjobb2026');

% =========================================================================
% SETTINGS
% =========================================================================
settings.dataFolder         = 'simulatedData';
settings.bomPricing         = 'DeterministicCashFlows';
settings.curFunctional      = 'EUR';
settings.startDate          = datenum(2007,1,1);
settings.endDate            = datenum(2024,12,31);
settings.usedItemNumbersOrg = [];
settings.usedProductNumbers = [];
settings.currencies         = {'AUD','CAD','CNY','EUR','GBP','SEK','USD','ZAR'};

% =========================================================================
% PIPELINE
% =========================================================================
fprintf('Loading market data (2007-2024)...\n'); tic;
dm = createDataMarket('reutersZero', settings);
fprintf('Done (%.1fs). %d dates, %d currencies\n\n', toc, length(dm.dates), length(dm.cName));

fprintf('Simulating transactions...\n'); tic;
createMatFilesSim(dm, 1, false);
dc = createDataCompany(dm, settings);
dp = buildPA(dm, dc);
fprintf('Done (%.1fs)\n\n', toc);

fprintf('Running performanceAttribution...\n'); tic;
dr = performanceAttribution(dm, dc, dp, false);
fprintf('Done (%.1fs)\n\n', toc);

% =========================================================================
% DERIVED QUANTITIES
% =========================================================================
M   = length(dm.dates);
Nc  = length(dm.cName);
N   = size(dp.Pbar, 2);
iEUR = find(ismember(dm.cName, 'EUR'));
iSEK = find(ismember(dm.cName, 'SEK'));

dateStrs = cellstr(datestr(dm.dates, 'yyyy-mm-dd'));

% Cumulative holdings
hI = [dp.hI0; repmat(dp.hI0,M-1,1) + ...
      cumsum(full(dp.xBI(2:end,:)) - full(dp.xSI(2:end,:)))];

% Cash in EUR equivalent
cashEUR = zeros(M, Nc);
for k = 1:Nc
  cashEUR(:,k) = dr.hC(:,k) .* dm.fx{k,iEUR};
end

% Instrument holdings by currency (EUR equiv)
hIPbar_byCcy = zeros(M, Nc);
for k = 1:Nc
  ind = find(dc.assets.pricingCurrency() == k);
  if ~isempty(ind)
    hIPbar_byCcy(:,k) = sum(hI(:,ind) .* dp.Pbar(:,ind), 2) .* dm.fx{k,iEUR};
  end
end

% Buy/sell volumes by currency (EUR equiv)
xBI_full = full(dp.xBI);
xSI_full = full(dp.xSI);
buyByCcy  = zeros(M, Nc);
sellByCcy = zeros(M, Nc);
for k = 1:Nc
  ind = find(dc.assets.pricingCurrency() == k);
  if ~isempty(ind)
    buyByCcy(:,k)  = sum(xBI_full(:,ind) .* dp.Pbar(:,ind), 2) .* dm.fx{k,iEUR};
    sellByCcy(:,k) = sum(xSI_full(:,ind) .* dp.Pbar(:,ind), 2) .* dm.fx{k,iEUR};
  end
end

% FX rates
ratesEUR = zeros(M, Nc);
ratesSEK = zeros(M, Nc);
for k = 1:Nc
  ratesEUR(:,k) = dm.fx{k,iEUR};
  ratesSEK(:,k) = dm.fx{k,iSEK};
end

% =========================================================================
% QUARTERLY & ANNUAL AGGREGATION
% =========================================================================
periodDates = makeQuarterDates(dm.dates(1), dm.dates(end));
nPeriods    = length(periodDates) - 1;
qLabels     = cellstr(datestr(periodDates(2:end), 'yyyy-Qq'));
[qYears,~,~]= datevec(periodDates(2:end));
uniqueYears = unique(qYears);
nYears      = length(uniqueYears);

TI_q=zeros(nPeriods,1); OCI_q=zeros(nPeriods,1);
CCt_q=zeros(nPeriods,1); CCtr_q=zeros(nPeriods,1); CCtl_q=zeros(nPeriods,1);
CCt_LY_q=zeros(nPeriods,1); CCtr_LY_q=zeros(nPeriods,1); CCtl_LY_q=zeros(nPeriods,1);

for p = 1:nPeriods
  idx = find(dm.dates > periodDates(p) & dm.dates <= periodDates(p+1));
  if ~isempty(idx)
    TI_q(p)      = sum(dr.dFX_trans(idx));
    OCI_q(p)     = sum(dr.dFX_transl(idx));
    CCt_q(p)     = sum(dr.dFX_cc(idx));
    CCtr_q(p)    = sum(dr.dFX_trans_CC(idx));
    CCtl_q(p)    = sum(dr.dFX_transl_CC(idx));
    CCt_LY_q(p)  = sum(dr.dFX_cc_LY_total(idx));
    CCtr_LY_q(p) = sum(dr.dFX_trans_CC_LY(idx));
    CCtl_LY_q(p) = sum(dr.dFX_transl_CC_LY(idx));
  end
end

TI_a=zeros(nYears,1); OCI_a=zeros(nYears,1);
CCt_a=zeros(nYears,1); CCtr_a=zeros(nYears,1); CCtl_a=zeros(nYears,1);
CCt_LY_a=zeros(nYears,1); CCtr_LY_a=zeros(nYears,1); CCtl_LY_a=zeros(nYears,1);

for y = 1:nYears
  qM = (qYears == uniqueYears(y));
  TI_a(y)      = sum(TI_q(qM));    OCI_a(y)     = sum(OCI_q(qM));
  CCt_a(y)     = sum(CCt_q(qM));   CCtr_a(y)    = sum(CCtr_q(qM));  CCtl_a(y)    = sum(CCtl_q(qM));
  CCt_LY_a(y)  = sum(CCt_LY_q(qM));CCtr_LY_a(y) = sum(CCtr_LY_q(qM)); CCtl_LY_a(y) = sum(CCtl_LY_q(qM));
end

% Console print
fprintf('=== Annual Results (SEK) ===\n');
fprintf('%-6s %13s %13s %13s %13s %13s\n','Year','TI','OCI','CC_total','CC_trans','CC_transl');
fprintf('%s\n',repmat('-',1,76));
for y = 1:nYears
  fprintf('%-6d %13.0f %13.0f %13.0f %13.0f %13.0f\n', ...
    uniqueYears(y),TI_a(y),OCI_a(y),CCt_a(y),CCtr_a(y),CCtl_a(y));
end
fprintf('%s\n',repmat('-',1,76));
fprintf('%-6s %13.0f %13.0f %13.0f %13.0f %13.0f\n','TOTAL', ...
  sum(TI_a),sum(OCI_a),sum(CCt_a),sum(CCtr_a),sum(CCtl_a));

% =========================================================================
% EXCEL EXPORT
% =========================================================================
xlFile = fullfile('C:/Users/jhybn/Desktop/exjobb/Exjobb_FX', 'PAM_full_export.xlsx');
fprintf('\nWriting %s ...\n', xlFile);

% Helper: convert datenum column to date strings
dn2s = @(v) cellstr(datestr(v, 'yyyy-mm-dd'));

% -------------------------------------------------------------------------
% Sheet 1: Annual
% -------------------------------------------------------------------------
hdrA = {'Year', ...
  'TI [SEK] (Eq.4.45 — Transactional FX)', ...
  'OCI [SEK] (Eq.4.46 — Translation FX)', ...
  'CC_total [SEK] (Eq.4.47)', ...
  'CC_trans_CompRates [SEK]', ...
  'CC_transl_CompRates [SEK]', ...
  'CC_total_LYRates [SEK]', ...
  'CC_trans_LYRates [SEK]', ...
  'CC_transl_LYRates [SEK]'};
aData = [num2cell(uniqueYears), num2cell([TI_a,OCI_a,CCt_a,CCtr_a,CCtl_a,CCt_LY_a,CCtr_LY_a,CCtl_LY_a])];
totRow = [{'TOTAL'}, num2cell([sum(TI_a),sum(OCI_a),sum(CCt_a),sum(CCtr_a),sum(CCtl_a),sum(CCt_LY_a),sum(CCtr_LY_a),sum(CCtl_LY_a)])];
writecell([hdrA; aData; totRow], xlFile, 'Sheet', 'Annual');
fprintf('  Sheet  1/16: Annual\n');

% -------------------------------------------------------------------------
% Sheet 2: Quarterly
% -------------------------------------------------------------------------
hdrQ = {'Quarter', ...
  'TI [SEK] (Eq.4.45)', ...
  'OCI [SEK] (Eq.4.46)', ...
  'CC_total [SEK] (Eq.4.47)', ...
  'CC_trans_CompRates [SEK]', ...
  'CC_transl_CompRates [SEK]', ...
  'CC_total_LYRates [SEK]', ...
  'CC_trans_LYRates [SEK]', ...
  'CC_transl_LYRates [SEK]'};
qData = [qLabels, num2cell([TI_q,OCI_q,CCt_q,CCtr_q,CCtl_q,CCt_LY_q,CCtr_LY_q,CCtl_LY_q])];
writecell([hdrQ; qData], xlFile, 'Sheet', 'Quarterly');
fprintf('  Sheet  2/16: Quarterly\n');

% -------------------------------------------------------------------------
% Sheet 3: Daily_PortfolioValue
% -------------------------------------------------------------------------
hdrPV = {'Date', ...
  'V_EUR [EUR] (Run1 — functional currency)', ...
  'V_SEK [SEK] (Run2 — actual rates)', ...
  'V_SEK_CompRates [SEK] (Run3 — all ccy at prior-year quarterly avg, Eq.4.47)', ...
  'V_SEK_TranslConst [SEK] (Run4 — actual trans rates x frozen EUR/SEK comp)', ...
  'V_SEK_LYRates [SEK] (Run5 — all ccy at last-year same-date rates)', ...
  'V_SEK_TranslLY [SEK] (Run6 — actual trans rates x last-year EUR/SEK)', ...
  'EUR/SEK_CompRate (prior-year quarterly avg EUR/SEK used in Run3/Run4)'};
pvData = [dateStrs, num2cell([dr.V_EUR, dr.V_SEK, dr.V_SEK_const, ...
  dr.V_SEK_transl_const, dr.V_SEK_LY, dr.V_SEK_transl_LY, dr.f_EUR_SEK_comp])];
writecell([hdrPV; pvData], xlFile, 'Sheet', 'Daily_PortfolioValue');
fprintf('  Sheet  3/16: Daily_PortfolioValue\n');

% -------------------------------------------------------------------------
% Sheet 4: Daily_FXImpact
% -------------------------------------------------------------------------
hdrFX = {'Date', ...
  'TI_daily [SEK] (Eq.4.45 — Transactional FX)', ...
  'OCI_daily [SEK] (Eq.4.46 — Translation FX)', ...
  'CC_total_daily [SEK] (Eq.4.47 — Constant-currency total)', ...
  'CC_trans_CompRates_daily [SEK] (Run3 vs Run4)', ...
  'CC_transl_CompRates_daily [SEK] (Run4 vs Run1)', ...
  'CC_total_LYRates_daily [SEK] (Run5 vs Run1)', ...
  'CC_trans_LYRates_daily [SEK] (Run5 vs Run6)', ...
  'CC_transl_LYRates_daily [SEK] (Run6 vs Run1)', ...
  'TI_cumulative [SEK]', ...
  'OCI_cumulative [SEK]', ...
  'CC_total_cumulative [SEK]', ...
  'CC_trans_CompRates_cumulative [SEK]', ...
  'CC_transl_CompRates_cumulative [SEK]', ...
  'CC_total_LYRates_cumulative [SEK]', ...
  'CC_trans_LYRates_cumulative [SEK]', ...
  'CC_transl_LYRates_cumulative [SEK]'};
fxData = [dateStrs, num2cell([ ...
  dr.dFX_trans, dr.dFX_transl, dr.dFX_cc, ...
  dr.dFX_trans_CC, dr.dFX_transl_CC, ...
  dr.dFX_cc_LY_total, dr.dFX_trans_CC_LY, dr.dFX_transl_CC_LY, ...
  cumsum(dr.dFX_trans), cumsum(dr.dFX_transl), cumsum(dr.dFX_cc), ...
  cumsum(dr.dFX_trans_CC), cumsum(dr.dFX_transl_CC), ...
  cumsum(dr.dFX_cc_LY_total), cumsum(dr.dFX_trans_CC_LY), cumsum(dr.dFX_transl_CC_LY)])];
writecell([hdrFX; fxData], xlFile, 'Sheet', 'Daily_FXImpact');
fprintf('  Sheet  4/16: Daily_FXImpact\n');

% -------------------------------------------------------------------------
% Sheet 5: Daily_PAMTerms — all PAM P&L decomposition terms
% -------------------------------------------------------------------------
hdrPAM = {'Date', ...
  'dI [EUR] (Interest on cash)', ...
  'dMf [EUR] (FX effect on cash holdings, h·R·df)', ...
  'dDf [EUR] (FX effect on dividends)', ...
  'dC [EUR] (Transaction costs — negative)', ...
  'dPtheta [EUR] (Term-structure carry)', ...
  'dPxi [EUR] (Linear FX/IR risk factor effects)', ...
  'dPq [EUR] (Quadratic FX/IR risk factor effects)', ...
  'dPa [EUR] (Taylor approximation residual)', ...
  'dPI [EUR] (Interest-rate precision residual)', ...
  'dPf [EUR] (FX effect on instruments, total price change)', ...
  'dPc [EUR] (Price-FX cross term / slippage)', ...
  'dFX_trans_EUR [EUR] (Transactional FX in EUR = dPf+dPc, Eq.4.45)'};
pamData = [dateStrs, num2cell([ ...
  dr.dVdI, dr.dVhRdf, dr.dVhDdf, dr.dVdC, ...
  dr.dVhdPtf, dr.dVhdPxif, dr.dVhdPqf, dr.dVhdepsaf, dr.dVhdepsIf, ...
  dr.dVhPtotdf, dr.dVhdepsf, dr.dFX_trans_EUR])];
writecell([hdrPAM; pamData], xlFile, 'Sheet', 'Daily_PAMTerms');
fprintf('  Sheet  5/16: Daily_PAMTerms\n');

% -------------------------------------------------------------------------
% Sheet 6: Daily_FXRates
% -------------------------------------------------------------------------
hdrRates = [{'Date'}, ...
  strcat(dm.cName', '_to_EUR'), ...
  strcat(dm.cName', '_to_SEK')];
ratesData = [dateStrs, num2cell([ratesEUR, ratesSEK])];
writecell([hdrRates; ratesData], xlFile, 'Sheet', 'Daily_FXRates');
fprintf('  Sheet  6/16: Daily_FXRates\n');

% -------------------------------------------------------------------------
% Sheet 7: Daily_CashHoldings
% -------------------------------------------------------------------------
hdrCash = [{'Date'}, ...
  strcat(dm.cName', '_cash_local'), ...
  strcat(dm.cName', '_cash_EUR_equiv')];
cashData = [dateStrs, num2cell([dr.hC, cashEUR])];
writecell([hdrCash; cashData], xlFile, 'Sheet', 'Daily_CashHoldings');
fprintf('  Sheet  7/16: Daily_CashHoldings\n');

% -------------------------------------------------------------------------
% Sheet 8: Daily_Instruments
% -------------------------------------------------------------------------
hdrInstr = [{'Date'}, strcat(dm.cName', '_instruments_EUR_equiv')];
instrData = [dateStrs, num2cell(hIPbar_byCcy)];
writecell([hdrInstr; instrData], xlFile, 'Sheet', 'Daily_Instruments');
fprintf('  Sheet  8/16: Daily_Instruments\n');

% -------------------------------------------------------------------------
% Sheet 9: Daily_Transactions
% -------------------------------------------------------------------------
hdrTx = [{'Date'}, ...
  strcat(dm.cName', '_buys_EUR_equiv'), ...
  strcat(dm.cName', '_sells_EUR_equiv')];
txData = [dateStrs, num2cell([buyByCcy, sellByCcy])];
writecell([hdrTx; txData], xlFile, 'Sheet', 'Daily_Transactions');
fprintf('  Sheet  9/16: Daily_Transactions\n');

% -------------------------------------------------------------------------
% Sheet 10: PortfolioSummary — EUR decomposition check
% -------------------------------------------------------------------------
hdrPS = {'Date', 'V_EUR [EUR]', 'V_SEK [SEK]', ...
  'Cash_total_EUR (sum across currencies)', ...
  'Instruments_total_EUR (sum across currencies)', ...
  'Cash + Instruments (should equal V_EUR)'};
hC_total_EUR     = sum(cashEUR, 2);
hIPbar_total_EUR = sum(hIPbar_byCcy, 2);
psData = [dateStrs, num2cell([dr.V_EUR, dr.V_SEK, ...
  hC_total_EUR, hIPbar_total_EUR, hC_total_EUR + hIPbar_total_EUR])];
writecell([hdrPS; psData], xlFile, 'Sheet', 'PortfolioSummary');
fprintf('  Sheet 10/16: PortfolioSummary\n');

% -------------------------------------------------------------------------
% Sheet 11: PurchaseOrders
% -------------------------------------------------------------------------
hdrPO = {'PurchaseOrderNumber', 'ItemNumber', 'TransactionCode', ...
  'Currency', 'Quantity', 'AccountingDate', 'DueDate', ...
  'LineAmount_OrderCurrency', 'CurrencyIndex'};
nPO = length(dc.p.purchaseOrderNumber);
poData = [num2cell(dc.p.purchaseOrderNumber(:)), ...
  num2cell(dc.p.itemNumber(:)), ...
  num2cell(dc.p.transactionCode(:)), ...
  dc.p.currency(:), ...
  num2cell(dc.p.invoicedQuantityAlternateUM(:)), ...
  dn2s(dc.p.accountingDate(:)), ...
  dn2s(dc.p.dueDate(:)), ...
  num2cell(dc.p.lineAmountOrderCurrency(:)), ...
  num2cell(dc.p.iCur(:))];
writecell([hdrPO; poData], xlFile, 'Sheet', 'PurchaseOrders');
fprintf('  Sheet 11/16: PurchaseOrders (%d rows)\n', nPO);

% -------------------------------------------------------------------------
% Sheet 12: StockTransactions
% -------------------------------------------------------------------------
hdrST = {'ItemNumber', 'TransactionType (25=procurement, 90=shrinkage)', ...
  'EntryDate', 'Quantity', 'NewOnHandBalance', 'ImpliedOnHandBalance', ...
  'OrderNumber', 'PurchaseOrderIndex'};
nST = length(dc.s.itemNumber);
stData = [num2cell(dc.s.itemNumber(:)), ...
  num2cell(dc.s.stockTransactionType(:)), ...
  dn2s(dc.s.entryDate(:)), ...
  num2cell(dc.s.transactionQuantityBasicUM(:)), ...
  num2cell(dc.s.newOnHandBalance(:)), ...
  num2cell(dc.s.impliedOnHandBalance(:)), ...
  num2cell(dc.s.orderNumber(:)), ...
  num2cell(dc.s.jPurchaseOrder(:))];
writecell([hdrST; stData], xlFile, 'Sheet', 'StockTransactions');
fprintf('  Sheet 12/16: StockTransactions (%d rows)\n', nST);

% -------------------------------------------------------------------------
% Sheet 13: AccountsReceivable
% -------------------------------------------------------------------------
hdrAR = {'InvoiceNumber', 'TransactionCode (10=invoice, 20=payment)', ...
  'AccountingDate', 'DueDate', 'ForeignCurrencyAmount', 'Currency', ...
  'CurrencyIndex', 'BondAssetIndex'};
nAR = length(dc.a.invoiceNumber);
arData = [num2cell(dc.a.invoiceNumber(:)), ...
  num2cell(dc.a.transactionCode(:)), ...
  dn2s(dc.a.accountingDate(:)), ...
  dn2s(dc.a.dueDate(:)), ...
  num2cell(dc.a.foreignCurrencyAmount(:)), ...
  dc.a.currency(:), ...
  num2cell(dc.a.iCur(:)), ...
  num2cell(dc.a.jBond(:))];
writecell([hdrAR; arData], xlFile, 'Sheet', 'AccountsReceivable');
fprintf('  Sheet 13/16: AccountsReceivable (%d rows)\n', nAR);

% -------------------------------------------------------------------------
% Sheet 14: AccountsPayable
% -------------------------------------------------------------------------
hdrAP = {'InvoiceNumber', 'TransactionCode (10=order, 20=payment)', ...
  'AccountingDate', 'DueDate', 'ForeignCurrencyAmount', 'Currency', ...
  'CurrencyIndex', 'BondAssetIndex'};
nAP = length(dc.ap.invoiceNumber);
apData = [num2cell(dc.ap.invoiceNumber(:)), ...
  num2cell(dc.ap.transactionCode(:)), ...
  dn2s(dc.ap.accountingDate(:)), ...
  dn2s(dc.ap.dueDate(:)), ...
  num2cell(dc.ap.foreignCurrencyAmount(:)), ...
  dc.ap.currency(:), ...
  num2cell(dc.ap.iCur(:)), ...
  num2cell(dc.ap.jBond(:))];
writecell([hdrAP; apData], xlFile, 'Sheet', 'AccountsPayable');
fprintf('  Sheet 14/16: AccountsPayable (%d rows)\n', nAP);

% -------------------------------------------------------------------------
% Sheet 15: Sales
% -------------------------------------------------------------------------
hdrSA = {'InvoiceNumber', 'ItemNumber', 'Currency', ...
  'ForeignCurrencyAmount', 'LineAmount_LocalCurrency_EUR', 'CostPrice_EUR', ...
  'CurrencyIndex'};
nSA = length(dc.sa.invoiceNumber);
saData = [num2cell(dc.sa.invoiceNumber(:)), ...
  num2cell(dc.sa.itemNumber(:)), ...
  dc.sa.currency(:), ...
  num2cell(dc.sa.foreignCurrencyAmount(:)), ...
  num2cell(dc.sa.lineAmountLocalCurrency(:)), ...
  num2cell(dc.sa.costPrice(:)), ...
  num2cell(dc.sa.iCur(:))];
writecell([hdrSA; saData], xlFile, 'Sheet', 'Sales');
fprintf('  Sheet 15/16: Sales (%d rows)\n', nSA);

% -------------------------------------------------------------------------
% Sheet 16: BOM
% -------------------------------------------------------------------------
hdrBOM = {'Product', 'ComponentNumber', 'Quantity', ...
  'ReferenceOrderNumber', 'ReportingDate', 'ActualFinishDate', ...
  'CostPrice_EUR', 'CostPriceValue_EUR', 'ProductIndex'};
nBOM = length(dc.b.product);
bomData = [num2cell(dc.b.product(:)), ...
  num2cell(dc.b.componentNumber(:)), ...
  num2cell(dc.b.quantity(:)), ...
  num2cell(dc.b.referenceOrderNumber(:)), ...
  dn2s(dc.b.reportingDate(:)), ...
  dn2s(dc.b.actualFinishDate(:)), ...
  num2cell(dc.b.costPrice(:)), ...
  num2cell(dc.b.CostPriceValue(:)), ...
  num2cell(dc.b.iProduct(:))];
writecell([hdrBOM; bomData], xlFile, 'Sheet', 'BOM');
fprintf('  Sheet 16/16: BOM (%d rows)\n', nBOM);

fprintf('\nDone. Excel written: %s\n', xlFile);
fprintf(['Sheets: Annual | Quarterly | Daily_PortfolioValue | Daily_FXImpact |\n' ...
         '        Daily_PAMTerms | Daily_FXRates | Daily_CashHoldings |\n' ...
         '        Daily_Instruments | Daily_Transactions | PortfolioSummary |\n' ...
         '        PurchaseOrders | StockTransactions | AccountsReceivable |\n' ...
         '        AccountsPayable | Sales | BOM\n']);
